//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marofh
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<BlokedUser> BlokedUsers { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<ContactUsMessage> ContactUsMessages { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<District> Districts { get; set; }
        public virtual DbSet<FAQ> FAQs { get; set; }
        public virtual DbSet<FavoriteList> FavoriteLists { get; set; }
        public virtual DbSet<FileType> FileTypes { get; set; }
        public virtual DbSet<Gallery> Galleries { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Mail> Mails { get; set; }
        public virtual DbSet<Nationality> Nationalities { get; set; }
        public virtual DbSet<NewsLetter> NewsLetters { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<OfficeDocument> OfficeDocuments { get; set; }
        public virtual DbSet<OfficeService> OfficeServices { get; set; }
        public virtual DbSet<Page> Pages { get; set; }
        public virtual DbSet<ReportedWorker> ReportedWorkers { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ServiceType> ServiceTypes { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<UserFamily> UserFamilies { get; set; }
        public virtual DbSet<WorkerCertificate> WorkerCertificates { get; set; }
        public virtual DbSet<WorkerCours> WorkerCourses { get; set; }
        public virtual DbSet<WorkerExpertis> WorkerExpertises { get; set; }
        public virtual DbSet<WorkerLanguage> WorkerLanguages { get; set; }
        public virtual DbSet<WorkerRequest> WorkerRequests { get; set; }
        public virtual DbSet<WorkerSkill> WorkerSkills { get; set; }
        public virtual DbSet<WorkerWorkingPlace> WorkerWorkingPlaces { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
    }
}
