//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marofh
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mail()
        {
            this.Mail1 = new HashSet<Mail>();
        }
    
        public int ID { get; set; }
        public string OfficeID { get; set; }
        public string OperatorID { get; set; }
        public string Message { get; set; }
        public Nullable<int> MailID { get; set; }
        public System.DateTime Date { get; set; }
        public bool IsRead { get; set; }
        public string FileUrl { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mail> Mail1 { get; set; }
        public virtual Mail Mail2 { get; set; }
    }
}
