//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marofh
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportedWorker
    {
        public int ID { get; set; }
        public string WorkerID { get; set; }
        public string OfficeID { get; set; }
        public string KafilID { get; set; }
        public System.DateTime ReportDate { get; set; }
        public bool HasFakeData { get; set; }
        public bool HasInappropriateImages { get; set; }
        public string Status { get; set; }
        public Nullable<bool> OtherReason { get; set; }
        public string Notes { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual AspNetUser AspNetUser2 { get; set; }
    }
}
