//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Marofh
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFamily
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int RealationshipTypeID { get; set; }
        public string UserID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
